// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"restful-to-mcp/internal/biz"
	"restful-to-mcp/internal/conf"
	"restful-to-mcp/internal/data"
	"restful-to-mcp/internal/data/database"
	"restful-to-mcp/internal/mcp/proxy"
	"restful-to-mcp/internal/mcp/server"
	"restful-to-mcp/internal/mcp/transformer/openapi"
	"restful-to-mcp/internal/pkg/cache"
	"restful-to-mcp/internal/pkg/startup"
	"restful-to-mcp/internal/service"
	"restful-to-mcp/middleware"
	"restful-to-mcp/pkg/logger"
	"restful-to-mcp/router"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// initApp init gin application.
func initApp(config *conf.Conf) (*gin.Engine, func(), error) {
	loggerLogger := logger.NewLogger(config)
	middlewareMiddleware := middleware.NewMiddleware(loggerLogger)
	registry := startup.NewRegistry(config, loggerLogger)
	transformer := openapi.NewConverter(loggerLogger)
	gormLogger := logger.NewGormLogger(loggerLogger)
	db, cleanup, err := database.NewPgClient(config, gormLogger, loggerLogger)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := cache.NewRedisClient(config, loggerLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	databaseData, cleanup3, err := database.NewData(db, client, loggerLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transaction := database.NewTransaction(databaseData)
	mcpServerRepo := data.NewMcpServerRepo(databaseData, loggerLogger)
	mcpFileRepo := data.NewMcpFileRepo(databaseData, loggerLogger)
	mcpFileUserCase := biz.NewMcpFileUserCase(mcpFileRepo, loggerLogger)
	mcpToolsRepo := data.NewMcpToolsRepo(databaseData, loggerLogger)
	memoryCache := cache.NewMemoryCache(loggerLogger)
	streamableHttpTransprot, cleanup4, err := server.NewMcpTransport(loggerLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpProxy := proxy.NewHttpProxy(loggerLogger, memoryCache)
	mcpServerManager, err := server.NewMcpServerManager(streamableHttpTransprot, httpProxy, loggerLogger, memoryCache)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	openapiUseCase := biz.NewOpenapiUserCase(transformer, loggerLogger, transaction, mcpServerRepo, mcpFileUserCase, mcpToolsRepo, config, memoryCache, mcpServerManager)
	ticker := startup.NewTicker(openapiUseCase, mcpServerManager)
	initializer := startup.NewInitializer(config, registry, ticker, loggerLogger, mcpServerManager, openapiUseCase)
	app := router.NewApp(middlewareMiddleware, config, initializer)
	openapiService := service.NewOpenapiService(openapiUseCase, loggerLogger)
	mcpConnectTokenRepo := data.NewMcpConnectToken(databaseData, loggerLogger)
	mcpServerUseCase := biz.NewMcpServerUseCase(mcpServerRepo, mcpConnectTokenRepo, loggerLogger)
	mcpServerService := service.NewMcpServerService(mcpServerUseCase, loggerLogger)
	mcpToolsUserCase := biz.NewMcpToolsUserCase(mcpToolsRepo, mcpServerRepo, loggerLogger, memoryCache)
	mcpToosService := service.NewMcpToosService(mcpToolsUserCase, loggerLogger)
	mcpGatewayUseCase := biz.NewMcpGatewayUseCase(loggerLogger)
	mcpGatewayService := service.NewMcpGatewayService(mcpGatewayUseCase, mcpServerUseCase, mcpServerManager, loggerLogger, memoryCache)
	engine := router.NewRouter(app, openapiService, mcpServerService, mcpToosService, mcpGatewayService)
	return engine, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
