// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flow-bridge-mcp/internal/biz"
	"flow-bridge-mcp/internal/conf"
	"flow-bridge-mcp/internal/data"
	"flow-bridge-mcp/internal/pkg/cache"
	"flow-bridge-mcp/internal/pkg/database"
	"flow-bridge-mcp/internal/service"
	"flow-bridge-mcp/middleware"
	"flow-bridge-mcp/pkg/logger"
	"flow-bridge-mcp/router"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// initApp init gin application.
func initApp(config *conf.Conf) (*gin.Engine, func(), error) {
	middlewareMiddleware := middleware.NewMiddleware()
	loggerLogger := logger.NewLogger(config)
	app := router.NewApp(middlewareMiddleware, config, loggerLogger)
	db, cleanup, err := database.NewPgClient(config, loggerLogger)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := cache.NewRedisClient(config, loggerLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(db, client, loggerLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	openapiRepo := data.NewOpenapiRepo(dataData, loggerLogger)
	openapiUseCase := biz.NewOpenapiUserCase(openapiRepo, loggerLogger)
	openapiService := service.NewOpenapiService(openapiUseCase, loggerLogger)
	engine := router.NewRouter(app, openapiService)
	return engine, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
